# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/morpho/C/NovaExpressRL

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/morpho/C/NovaExpressRL

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/morpho/C/NovaExpressRL/CMakeFiles /home/morpho/C/NovaExpressRL//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/morpho/C/NovaExpressRL/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named shaders

# Build rule for target.
shaders: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 shaders
.PHONY : shaders

# fast build rule for target.
shaders/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shaders.dir/build.make CMakeFiles/shaders.dir/build
.PHONY : shaders/fast

#=============================================================================
# Target rules for targets named vma

# Build rule for target.
vma: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vma
.PHONY : vma

# fast build rule for target.
vma/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vma.dir/build.make CMakeFiles/vma.dir/build
.PHONY : vma/fast

#=============================================================================
# Target rules for targets named rogue

# Build rule for target.
rogue: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rogue
.PHONY : rogue

# fast build rule for target.
rogue/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rogue.dir/build.make CMakeFiles/rogue.dir/build
.PHONY : rogue/fast

extern/vma.o: extern/vma.cpp.o
.PHONY : extern/vma.o

# target to build an object file
extern/vma.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vma.dir/build.make CMakeFiles/vma.dir/extern/vma.cpp.o
.PHONY : extern/vma.cpp.o

extern/vma.i: extern/vma.cpp.i
.PHONY : extern/vma.i

# target to preprocess a source file
extern/vma.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vma.dir/build.make CMakeFiles/vma.dir/extern/vma.cpp.i
.PHONY : extern/vma.cpp.i

extern/vma.s: extern/vma.cpp.s
.PHONY : extern/vma.s

# target to generate assembly for a file
extern/vma.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vma.dir/build.make CMakeFiles/vma.dir/extern/vma.cpp.s
.PHONY : extern/vma.cpp.s

src/allocator.o: src/allocator.c.o
.PHONY : src/allocator.o

# target to build an object file
src/allocator.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rogue.dir/build.make CMakeFiles/rogue.dir/src/allocator.c.o
.PHONY : src/allocator.c.o

src/allocator.i: src/allocator.c.i
.PHONY : src/allocator.i

# target to preprocess a source file
src/allocator.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rogue.dir/build.make CMakeFiles/rogue.dir/src/allocator.c.i
.PHONY : src/allocator.c.i

src/allocator.s: src/allocator.c.s
.PHONY : src/allocator.s

# target to generate assembly for a file
src/allocator.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rogue.dir/build.make CMakeFiles/rogue.dir/src/allocator.c.s
.PHONY : src/allocator.c.s

src/bios.o: src/bios.c.o
.PHONY : src/bios.o

# target to build an object file
src/bios.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rogue.dir/build.make CMakeFiles/rogue.dir/src/bios.c.o
.PHONY : src/bios.c.o

src/bios.i: src/bios.c.i
.PHONY : src/bios.i

# target to preprocess a source file
src/bios.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rogue.dir/build.make CMakeFiles/rogue.dir/src/bios.c.i
.PHONY : src/bios.c.i

src/bios.s: src/bios.c.s
.PHONY : src/bios.s

# target to generate assembly for a file
src/bios.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rogue.dir/build.make CMakeFiles/rogue.dir/src/bios.c.s
.PHONY : src/bios.c.s

src/controls.o: src/controls.c.o
.PHONY : src/controls.o

# target to build an object file
src/controls.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rogue.dir/build.make CMakeFiles/rogue.dir/src/controls.c.o
.PHONY : src/controls.c.o

src/controls.i: src/controls.c.i
.PHONY : src/controls.i

# target to preprocess a source file
src/controls.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rogue.dir/build.make CMakeFiles/rogue.dir/src/controls.c.i
.PHONY : src/controls.c.i

src/controls.s: src/controls.c.s
.PHONY : src/controls.s

# target to generate assembly for a file
src/controls.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rogue.dir/build.make CMakeFiles/rogue.dir/src/controls.c.s
.PHONY : src/controls.c.s

src/drawing.o: src/drawing.c.o
.PHONY : src/drawing.o

# target to build an object file
src/drawing.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rogue.dir/build.make CMakeFiles/rogue.dir/src/drawing.c.o
.PHONY : src/drawing.c.o

src/drawing.i: src/drawing.c.i
.PHONY : src/drawing.i

# target to preprocess a source file
src/drawing.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rogue.dir/build.make CMakeFiles/rogue.dir/src/drawing.c.i
.PHONY : src/drawing.c.i

src/drawing.s: src/drawing.c.s
.PHONY : src/drawing.s

# target to generate assembly for a file
src/drawing.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rogue.dir/build.make CMakeFiles/rogue.dir/src/drawing.c.s
.PHONY : src/drawing.c.s

src/dungeon.o: src/dungeon.c.o
.PHONY : src/dungeon.o

# target to build an object file
src/dungeon.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rogue.dir/build.make CMakeFiles/rogue.dir/src/dungeon.c.o
.PHONY : src/dungeon.c.o

src/dungeon.i: src/dungeon.c.i
.PHONY : src/dungeon.i

# target to preprocess a source file
src/dungeon.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rogue.dir/build.make CMakeFiles/rogue.dir/src/dungeon.c.i
.PHONY : src/dungeon.c.i

src/dungeon.s: src/dungeon.c.s
.PHONY : src/dungeon.s

# target to generate assembly for a file
src/dungeon.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rogue.dir/build.make CMakeFiles/rogue.dir/src/dungeon.c.s
.PHONY : src/dungeon.c.s

src/fov.o: src/fov.c.o
.PHONY : src/fov.o

# target to build an object file
src/fov.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rogue.dir/build.make CMakeFiles/rogue.dir/src/fov.c.o
.PHONY : src/fov.c.o

src/fov.i: src/fov.c.i
.PHONY : src/fov.i

# target to preprocess a source file
src/fov.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rogue.dir/build.make CMakeFiles/rogue.dir/src/fov.c.i
.PHONY : src/fov.c.i

src/fov.s: src/fov.c.s
.PHONY : src/fov.s

# target to generate assembly for a file
src/fov.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rogue.dir/build.make CMakeFiles/rogue.dir/src/fov.c.s
.PHONY : src/fov.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rogue.dir/build.make CMakeFiles/rogue.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rogue.dir/build.make CMakeFiles/rogue.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rogue.dir/build.make CMakeFiles/rogue.dir/src/main.c.s
.PHONY : src/main.c.s

src/map.o: src/map.c.o
.PHONY : src/map.o

# target to build an object file
src/map.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rogue.dir/build.make CMakeFiles/rogue.dir/src/map.c.o
.PHONY : src/map.c.o

src/map.i: src/map.c.i
.PHONY : src/map.i

# target to preprocess a source file
src/map.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rogue.dir/build.make CMakeFiles/rogue.dir/src/map.c.i
.PHONY : src/map.c.i

src/map.s: src/map.c.s
.PHONY : src/map.s

# target to generate assembly for a file
src/map.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rogue.dir/build.make CMakeFiles/rogue.dir/src/map.c.s
.PHONY : src/map.c.s

src/mobs.o: src/mobs.c.o
.PHONY : src/mobs.o

# target to build an object file
src/mobs.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rogue.dir/build.make CMakeFiles/rogue.dir/src/mobs.c.o
.PHONY : src/mobs.c.o

src/mobs.i: src/mobs.c.i
.PHONY : src/mobs.i

# target to preprocess a source file
src/mobs.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rogue.dir/build.make CMakeFiles/rogue.dir/src/mobs.c.i
.PHONY : src/mobs.c.i

src/mobs.s: src/mobs.c.s
.PHONY : src/mobs.s

# target to generate assembly for a file
src/mobs.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rogue.dir/build.make CMakeFiles/rogue.dir/src/mobs.c.s
.PHONY : src/mobs.c.s

src/terrain.o: src/terrain.c.o
.PHONY : src/terrain.o

# target to build an object file
src/terrain.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rogue.dir/build.make CMakeFiles/rogue.dir/src/terrain.c.o
.PHONY : src/terrain.c.o

src/terrain.i: src/terrain.c.i
.PHONY : src/terrain.i

# target to preprocess a source file
src/terrain.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rogue.dir/build.make CMakeFiles/rogue.dir/src/terrain.c.i
.PHONY : src/terrain.c.i

src/terrain.s: src/terrain.c.s
.PHONY : src/terrain.s

# target to generate assembly for a file
src/terrain.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rogue.dir/build.make CMakeFiles/rogue.dir/src/terrain.c.s
.PHONY : src/terrain.c.s

src/ui.o: src/ui.c.o
.PHONY : src/ui.o

# target to build an object file
src/ui.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rogue.dir/build.make CMakeFiles/rogue.dir/src/ui.c.o
.PHONY : src/ui.c.o

src/ui.i: src/ui.c.i
.PHONY : src/ui.i

# target to preprocess a source file
src/ui.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rogue.dir/build.make CMakeFiles/rogue.dir/src/ui.c.i
.PHONY : src/ui.c.i

src/ui.s: src/ui.c.s
.PHONY : src/ui.s

# target to generate assembly for a file
src/ui.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rogue.dir/build.make CMakeFiles/rogue.dir/src/ui.c.s
.PHONY : src/ui.c.s

src/vulkan_backend.o: src/vulkan_backend.c.o
.PHONY : src/vulkan_backend.o

# target to build an object file
src/vulkan_backend.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rogue.dir/build.make CMakeFiles/rogue.dir/src/vulkan_backend.c.o
.PHONY : src/vulkan_backend.c.o

src/vulkan_backend.i: src/vulkan_backend.c.i
.PHONY : src/vulkan_backend.i

# target to preprocess a source file
src/vulkan_backend.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rogue.dir/build.make CMakeFiles/rogue.dir/src/vulkan_backend.c.i
.PHONY : src/vulkan_backend.c.i

src/vulkan_backend.s: src/vulkan_backend.c.s
.PHONY : src/vulkan_backend.s

# target to generate assembly for a file
src/vulkan_backend.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rogue.dir/build.make CMakeFiles/rogue.dir/src/vulkan_backend.c.s
.PHONY : src/vulkan_backend.c.s

src/wfc.o: src/wfc.c.o
.PHONY : src/wfc.o

# target to build an object file
src/wfc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rogue.dir/build.make CMakeFiles/rogue.dir/src/wfc.c.o
.PHONY : src/wfc.c.o

src/wfc.i: src/wfc.c.i
.PHONY : src/wfc.i

# target to preprocess a source file
src/wfc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rogue.dir/build.make CMakeFiles/rogue.dir/src/wfc.c.i
.PHONY : src/wfc.c.i

src/wfc.s: src/wfc.c.s
.PHONY : src/wfc.s

# target to generate assembly for a file
src/wfc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rogue.dir/build.make CMakeFiles/rogue.dir/src/wfc.c.s
.PHONY : src/wfc.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... shaders"
	@echo "... rogue"
	@echo "... vma"
	@echo "... extern/vma.o"
	@echo "... extern/vma.i"
	@echo "... extern/vma.s"
	@echo "... src/allocator.o"
	@echo "... src/allocator.i"
	@echo "... src/allocator.s"
	@echo "... src/bios.o"
	@echo "... src/bios.i"
	@echo "... src/bios.s"
	@echo "... src/controls.o"
	@echo "... src/controls.i"
	@echo "... src/controls.s"
	@echo "... src/drawing.o"
	@echo "... src/drawing.i"
	@echo "... src/drawing.s"
	@echo "... src/dungeon.o"
	@echo "... src/dungeon.i"
	@echo "... src/dungeon.s"
	@echo "... src/fov.o"
	@echo "... src/fov.i"
	@echo "... src/fov.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/map.o"
	@echo "... src/map.i"
	@echo "... src/map.s"
	@echo "... src/mobs.o"
	@echo "... src/mobs.i"
	@echo "... src/mobs.s"
	@echo "... src/terrain.o"
	@echo "... src/terrain.i"
	@echo "... src/terrain.s"
	@echo "... src/ui.o"
	@echo "... src/ui.i"
	@echo "... src/ui.s"
	@echo "... src/vulkan_backend.o"
	@echo "... src/vulkan_backend.i"
	@echo "... src/vulkan_backend.s"
	@echo "... src/wfc.o"
	@echo "... src/wfc.i"
	@echo "... src/wfc.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

